services:
  - type: web
    name: multilangsetu
    env: python
    pythonVersion: 3.12
    region: oregon # or your preferred region
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    autoDeploy: true

  - type: static
    name: multilangsetu-static
    env: static
    plan: free
    routes:
      - type: web_service
        src: "/static/(.*)"
        dest: "/static/$1"
    autoDeploy: true